trigger:
  - pr  
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: buildId
    value: $(Build.BuildId)
  - name: buildNumber
    value: $(Build.BuildNumber)
  - name: buildConfiguration
    value: 'Release'
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: outputPackDir
    ${{ if eq(variables.isMaster, 'true') }}:
      value: '$(Build.ArtifactStagingDirectory)/Nupkgs/Stable'
    ${{else}}:
      value: '$(Build.ArtifactStagingDirectory)/Nupkgs/Pre'
  - name: packConfiguration
    ${{ if eq(variables.isMaster, 'true') }}:
      value: $(buildConfiguration)
    ${{else}}:
      value: 'Debug'
  - name: tagName
    value: '$(GitVersion.InformationalVersion)+$(buildNumber)+$(buildId)'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Use GitVersion
  name: GitVersion

- script: |
      echo ${{ variables.one }} # outputs initialValue
      echo $(outputPackDir)
      echo $(packConfiguration)
      echo $(tagName)

- task: PublishPipelineArtifact@1
  displayName: 'Publish pipeline Artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
    publishLocation: 'Container'

- script: |
    git tag $(tagName)
    git push origin $(tagName)
  workingDirectory: $(Build.SourcesDirectory)