name: '$(Rev:r)'

trigger:
  - pr
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: buildConfiguration
    value: 'Release'
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: outputPackDir
    ${{ if eq(variables.isMaster, 'true') }}:
      value: '$(Build.ArtifactStagingDirectory)/Nupkgs/Stable'
    ${{else}}:
      value: '$(Build.ArtifactStagingDirectory)/Nupkgs/Pre'
  - name: packConfiguration
    ${{ if eq(variables.isMaster, 'true') }}:
      value: $(buildConfiguration)
    ${{else}}:
      value: 'Debug'
  - name: tagName
    ${{ if eq(variables.isMaster, 'false') }}:
      value: '$(GitVersion.SemVer)'
    ${{else}}:
      value: '$(GitVersion.InformationalVersion).$(buildNumber)'

steps:
# This is a special way to retrieve the pipeline $(Rev:r) and store it in a variable
# It is also linked to the first line of code "name: '$(Rev:r)'"
# It also need to be the first thing to run
- script: |
      echo "##vso[task.setvariable variable=buildNumber;]$(Build.BuildNumber)"

- checkout: self
  persistCredentials: true
  fetchTags: false

- script: |
    git checkout $(System.PullRequest.SourceBranch)
    git switch $(System.PullRequest.SourceBranch)
  condition: eq(variables['Build.Reason'], 'PullRequest')
  displayName: Checkout source branch

- task: gitversion/setup@3.0.3
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@3.0.3
  displayName: Use GitVersion
  name: GitVersion
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'

- script: |
      echo $(outputPackDir)
      echo $(packConfiguration)
      echo $(tagName)
      echo ${{ variables['Build.SourceBranch'] }}
      echo $(Build.SourceBranch)

- task: PublishPipelineArtifact@1
  displayName: 'Publish pipeline Artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
    publishLocation: 'Container'

- script: |
    git tag $(tagName)
    git push origin $(tagName)
  condition: ne(variables['Build.Reason'], 'PullRequest')
  workingDirectory: $(Build.SourcesDirectory)